export const propertiesOrder = [
  // General
  'content',
  'position',
  'display',
  'z-index',
  'overflow',
  'overflow-x',
  'overflow-y',
  'opacity',
  'visibility',
  'object-fit',
  'object-position',
  'box-sizing',
  'outline',
  // Flex
  'flex-direction',
  'flex',
  // Grid
  'grid-template-areas',
  'grid-template-columns',
  'grid-template-rows',
  'grid-auto-columns',
  'grid-auto-rows',
  'grid-column',
  'grid-row',
  'grid-area',
  'gap',
  'column-gap',
  'row-gap',
  // Adjustment
  'align-items',
  'align-self',
  'align-content',
  'justify-items',
  'justify-self',
  'justify-content',
  // Positioning
  'top',
  'bottom',
  'left',
  'right',
  // Dimensions
  'width',
  'height',
  'min-width',
  'min-height',
  'max-width',
  'max-height',
  // Margin and padding
  'margin',
  'margin-top',
  'margin-bottom',
  'margin-left',
  'margin-right',
  'padding',
  'padding-top',
  'padding-bottom',
  'padding-left',
  'padding-right',
  // Border
  'border',
  'border-style',
  'border-color',
  'border-width',
  'border-top',
  'border-top-style',
  'border-top-color',
  'border-top-width',
  'border-bottom',
  'border-bottom-style',
  'border-bottom-color',
  'border-bottom-width',
  'border-left',
  'border-left-style',
  'border-left-color',
  'border-left-width',
  'border-right',
  'border-right-style',
  'border-right-color',
  'border-right-width',
  'border-radius',
  'border-radius-top-left',
  'border-radius-top-right',
  'border-radius-bottom-left',
  'border-radius-bottom-right',
  // Colors
  'background-color',
  'background-image',
  'background-origin',
  'background-position',
  'background-position-x',
  'background-position-y',
  'background-url',
  'background-repeat',
  'background-size',
  'color',
  // Text
  'font-family',
  'font-size',
  'font-weight',
  'font-style',
  'font-display',
  'line-height',
  'letter-spacing',
  'text-decoration',
  'text-transform',
  'text-align',
  'text-overflow',
  'vertical-align',
  'white-space',
  // SVG
  'stroke',
  'stroke-width',
  'stroke-color',
  'stroke-dasharray',
  'stroke-dashoffset',
  'stroke-linecap',
  'fill',
  'fill-width',
  'fill-color',
  // Transform
  'animation',
  'transition',
  'transform',
  'transform-origin',
  'rotate',
  // Shadows
  'box-shadow',
  'text-shadow',
  // Cursor
  'cursor',
  'pointer-events',
  'user-select',
  // Font declaration
  'src',
  'unicode-range',
  // Counters
  'counter-increment',
  'counter-reset'
]

export const cowtech = {
  extends: ['stylelint-config-standard-scss', 'stylelint-config-prettier-scss'],
  plugins: ['stylelint-order'],
  rules: {
    'color-function-notation': null,
    // This is to enable emptyLineBeforeUnspecified in order/properties-order to work
    'declaration-empty-line-before': ['never', { ignore: 'after-declaration' }],
    // This doesn't work with CSS nesting, see https://github.com/stylelint/stylelint/issues/8849
    'no-descending-specificity': null,
    'media-feature-range-notation': null,
    'order/properties-order': [
      propertiesOrder,
      { unspecified: 'bottomAlphabetical', emptyLineBeforeUnspecified: 'always' }
    ],
    'value-keyword-case': null
  }
}

export default cowtech
